name: CD

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Staging deploy
      uses: vitalyliber/dokku-github-action@v6.0
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        HOST: ${{ secrets.IP }}
        PROJECT: app
        APP_CONFIG: ${{ secrets.APP_CONFIG }}
  sync:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Create zip file
      run: git archive -o petal.zip HEAD
    - name: Make zip dir
      run: mkdir zipped
    - name: Move into zip dir
      run: mv petal.zip ./zipped
    - name: Push zip to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --delete
      env:
        SOURCE_DIR: './zipped'
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}

